# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:59
from __future__ import unicode_literals

from django.db import migrations

import os
from django.contrib.gis.utils import LayerMapping

world_mapping = {
    'fips' : 'FIPS',
    'iso2' : 'ISO2',
    'iso3' : 'ISO3',
    'un' : 'UN',
    'name' : 'NAME',
    'area' : 'AREA',
    'pop2005' : 'POP2005',
    'region' : 'REGION',
    'subregion' : 'SUBREGION',
    'lon' : 'LON',
    'lat' : 'LAT',
    'mpoly' : 'MULTIPOLYGON',
}

world_shp = os.path.abspath(
    os.path.join(os.path.dirname(__file__), '../data', 'TM_WORLD_BORDERS-0.3.shp'),
)

def forwards_func(apps, schema_editor):
    WorldBorder = apps.get_model('world', 'WorldBorder')
    lm = LayerMapping(
        WorldBorder, world_shp, world_mapping,
        transform=False, encoding='iso-8859-1',
    )
    lm.save(strict=True, verbose=False)

def reverse_func(apps, schema_editor):
    WorldBorder = apps.get_model('world', 'WorldBorder')
    WorldBorder.objects.all.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
