# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20170506_1959'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadmetric',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='world.WorldBorder'),
        ),
    ]
